# Generated by Django 5.2.8 on 2025-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GalleryModel",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("path", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
